version: "1"
services:
  mysql:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    volumes:
      - "/mydata/mysql/log:/var/log/mysql"
      - "/mydata/mysql/data:/var/lib/mysql"
#      - "/mydata/mysql/conf:/etc/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - "mydata/redis/data:/data"
      - "mydata/redis/conf/redis.conf:/etc/redis/redis.conf"
    command: ["redis-server", "/etc/redis/redis.conf"]
